# Generated by Django 4.2.4 on 2023-08-21 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='date',
            field=models.DateField(unique=True, verbose_name='Date'),
        ),
    ]
