# Generated by Django 4.2.4 on 2023-08-21 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_dino_hatched_dino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dino',
            name='hatched_dino',
        ),
    ]
