# Generated by Django 4.2.4 on 2023-08-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_dino_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dino',
            name='name',
            field=models.CharField(choices=[('Doux', 'Doux'), ('Kira', 'Kira'), ('Kuro', 'Kuro'), ('Loki', 'Loki'), ('Mono', 'Mono'), ('Mort', 'Mort'), ('Nico', 'Nico'), ('Olaf', 'Olaf'), ('Tart', 'Tart'), ('Vita', 'Vita')], default=1, max_length=20),
        ),
    ]
