# Generated by Django 4.2.4 on 2023-08-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_dino_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dino',
            name='colour',
            field=models.CharField(choices=[('Blue', 'Blue'), ('Pink', 'Pink'), ('Grey', 'Grey'), ('Dark Blue', 'Dark Blue'), ('Light Grey', 'Light Grey'), ('Red', 'Red'), ('Orange', 'Orange'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Dark Green', 'Dark Green')], default=1),
        ),
        migrations.AlterField(
            model_name='dino',
            name='name',
            field=models.CharField(default='Dino', max_length=20),
        ),
    ]
