# Generated by Django 4.2.4 on 2023-08-23 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_animation_dino_animation_collection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animation',
            old_name='dino',
            new_name='dino_colour',
        ),
        migrations.AlterField(
            model_name='dino',
            name='animation_collection',
            field=models.ManyToManyField(choices=[('IDLE', 'Idle'), ('MOVE', 'Move'), ('KICK', 'Kick'), ('HURT', 'Hurt'), ('DASH', 'Dash'), ('BITE', 'Bite'), ('DEAD', 'dead'), ('JUMP', 'Jump')], default=1, to='main_app.animation'),
        ),
    ]
