# Generated by Django 4.2.4 on 2023-08-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_dino_animation_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
