# Generated by Django 4.2.4 on 2023-08-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_field_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='duration',
            field=models.CharField(default='0'),
        ),
    ]
