# Generated by Django 4.2.4 on 2023-08-24 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_remove_animation_dino_colour_remove_animation_url_and_more'),
    ]

    operations = [
    ]
