# Generated by Django 4.2.4 on 2023-08-24 02:02

from django.db import migrations
from main_app.models import Animation

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20230824_0201'),
    ]

    operations = [
    ]

