# Generated by Django 4.2.4 on 2023-08-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20230824_0202'),
    ]

    operations = [
    ]
