# Generated by Django 4.2.4 on 2023-08-24 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_animation_action'),
        ('main_app', '0017_alter_animation_action'),
    ]

    operations = [
    ]
