# Generated by Django 4.2.4 on 2023-08-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_alter_animation_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
